// The words of the two cost calculators (owner's calculators of 06 October 2026, reviewed and
// refined). Both price the professional time spent on the evidence in a construction dispute, and
// both show the time a shared, searchable record of the discussion might free as an illustration
// drawn from general research, never as a measured result of VeriCase. The figures behind the
// words are in src/calculators; the sources are verified in the capability register (E15).
// Placeholders in {braces} are filled by the page; [words](href) is a link.

export { CALCULATOR_GATE } from './calculatorLinks';

// Shared labels.
export const CALCULATORS = {
  eyebrow: 'Cost calculator',
  keyLabel: 'What each label means',
  basis: { pub: 'Published', ven: 'Company or vendor', asm: 'VeriCase assumption', own: 'Your figure' },
  basisMeaning: {
    pub: 'an official, surveyed or court figure, or one derived from published data',
    ven: 'reported by a company, or by a study a vendor commissioned',
    asm: 'an estimate by VeriCase that you can change',
    own: 'a figure you have entered',
  },
  rateBasis: { guideline: 'Guideline rate', courtRecord: 'Court record', panel: 'Panel rate', chambers: 'Chambers', survey: 'Survey', derived: 'Derived', assumption: 'Assumption', yours: 'Your rate' },
  activities: {
    email: { name: 'Discussing the evidence', short: 'Discussing' },
    search: { name: 'Finding earlier replies', short: 'Finding' },
    meet: { name: 'Meetings', short: 'Meetings' },
    read: { name: 'Reading and rereading', short: 'Reading' },
    bund: { name: 'Bundling', short: 'Bundling' },
  },
  // What each central reduction rests on (keys from src/calculators/reductions.js).
  reductionBasis: {
    published: { cls: 'pub', text: 'McKinsey Global Institute, July 2012 ({range})' },
    abovePublished: { cls: 'own', text: 'Above the published range of {range}' },
    none: { text: 'None counted' },
    noneAssumed: { text: 'None counted in the central case: no study measures this' },
    noneMeasured: { text: 'None counted: no independent study measures it' },
    shopify: { cls: 'ven', text: 'Shopify, 2023, reported by the company' },
    forrester: { cls: 'ven', text: 'Forrester for Microsoft, 2019, commissioned by the vendor' },
    withinVendor: { cls: 'ven', text: 'Within the company and vendor figures' },
    aboveVendor: { cls: 'own', text: 'Above any published figure' },
    assumption: { cls: 'asm', text: 'No study measures this' },
    yours: { cls: 'own', text: '' },
  },
  ranges: { email: '25% to 30%', search: '30% to 35%' },
  reductionColumns: ['Activity', 'Low, %', 'Central, %', 'High, %', 'Basis of the central case'],
  caseNames: { lo: 'low', c: 'central', hi: 'high' },
  pubOnly: {
    label: 'Central case: published research only',
    hint: 'Leaves out of the central case the reductions that no study measures (reading and bundling) and the company and vendor figures for meetings. Untick it to include them.',
  },
  sheet: {
    title: 'The timesheet',
    one: 'One square is one working day of {day} hours, five to a row.',
    many: 'One square is {n} working days of {day} hours, five to a row.',
    total: '{days} days',
    label: '{days} working days, of which about {freed} might be freed',
    freed: 'Might be freed',
  },
  freedTitle: 'Time a shared record might free, central case',
  caveat:
    'An illustration, not a measured result. It applies published research on shared, searchable discussion, made for knowledge workers generally, to the figures above; VeriCase has not measured how much time it saves. Whether time freed becomes a saving depends on how the time is billed and used.',
  recover: {
    adj: 'In statutory adjudication each party usually bears its own legal and expert costs, so the cost of this time is not usually recoverable from the other party.',
    court: 'In litigation some of these costs may be recoverable from, or payable to, the other party. The figures are the cost of time spent, not recoverable costs.',
    arb: 'In arbitration some of these costs may be recoverable from, or payable to, the other party. The figures are the cost of time spent, not recoverable costs.',
  },
  nothingToShow: 'Nothing to show',
  tableLabel: 'Table: {title}',
  noTime: 'No time entered.',
  noOne: 'No one selected.',
  total: 'Total',
  seeBreakdown: 'See the breakdown',
  print: 'Print or save this estimate',
  restore: 'Restore the starting rates and reductions',
  live: 'Modelled cost {cost}. Might be freed in the central case: {freed}.',
  mobileLabel: 'Modelled cost',
};

// The discussion cost calculator: built up from each item of evidence and each time it is
// discussed. Its adjudication starting point is note 3's model on the home page.
export const DISCUSSION_COST = {
  path: '/discussion-cost',
  h1: 'What does discussing the evidence cost?',
  intro: [
    'Choose a starting point, then adjust the matter, the team, the rates and the time to match your own. The calculator prices the professional time your team spends discussing the evidence, finding earlier replies, meeting, reading and bundling, and shows how much of that time a shared, searchable record of the discussion might free.',
    'The adjudication starting point is the model behind the figure in the [collaboration section of our home page](/#collaboration): 120 rounds of discussion at 40 minutes a round, which cost £18,318.60. Every rate and reduction is labelled with its basis, and the time estimates are tested against published studies as you change them. Nothing you enter leaves your browser.',
  ],
  other: 'Prefer to start from each person’s hours on the matter? Use the [evidence cost calculator](/evidence-cost).',
  matter: {
    legend: 'The matter',
    note: 'Each starting point is a VeriCase estimate, built from the same minutes and hours for each person. Change any figure to match your matter.',
    startLegend: 'Starting point',
    starts: { adj: 'Adjudication', large: 'Large adjudication', court: 'Court claim', arb: 'Arbitration' },
    status: {
      adj: 'Seven people over about six weeks: 40 items, each discussed three times (120 rounds), two bundles, one conference with counsel, one experts’ meeting and three progress calls. Discussion takes 40 minutes a round, as in the model on our home page.',
      large: 'Fourteen people over twelve weeks: counsel, four grades of solicitor, five experts and three of the client’s people. 100 items, each discussed three times, three bundles, six conferences with counsel, eight experts’ meetings and twelve progress calls.',
      court: '300 items, each discussed three times (900 rounds), over about two years, with four bundles and a progress call every fortnight. The discussion line is the base case of the model on our home page.',
      arb: '250 items, each discussed three times (750 rounds), over about 20 months, with four bundles and two progress calls a month, using the same times for each person as the adjudication.',
    },
    custom: 'Your own settings, starting from the {start} example.',
    items: { label: 'Items of evidence discussed', hint: 'Emails, notices, records, drawings and reports that the team has to read and discuss.' },
    rounds: { label: 'Times each item is discussed', hint: 'Each time is a round of replies before the point is settled.', once: 'once', twice: 'twice', many: '{n} times' },
    bundles: { label: 'Bundles prepared', hint: 'Submission or hearing bundles, each indexed and paginated.', none: 'none', words: ['bundle', 'bundles'] },
    weeks: { label: 'Length of the matter', hint: 'Used only to test the time estimates against weekly benchmarks; the cost does not depend on it.', words: ['week', 'weeks'], months: ', about {m} months' },
    matters: { label: 'Number of matters', hint: 'For a series of adjudications on one project. No credit is taken for reusing earlier discussion.' },
    forum: { label: 'Forum', options: { adj: 'Statutory adjudication', court: 'Court (Technology and Construction Court)', arb: 'Arbitration' } },
  },
  rates: {
    legend: 'Rates',
    note: 'Choose the source of the solicitors’ rates. Counsel’s and the experts’ rates can be chosen from published figures or typed over in the team table.',
    band: { label: 'Solicitors’ rates', options: { l1: 'Guideline rates 2026, London 1', l2: 'Guideline rates 2026, London 2', l3: 'Guideline rates 2026, London 3', n1: 'Guideline rates 2026, National 1', n2: 'Guideline rates 2026, National 2', mkt: 'Rates claimed in a Technology and Construction Court case (2025)' } },
    kc: { label: 'King’s Counsel', options: { 600: '£600: VeriCase assumption', 270: '£270: Attorney General’s panel rate, King’s Counsel of ten years or more', 1000: '£1,000: upper sensitivity, VeriCase assumption' }, own: 'Your own rate' },
    jun: { label: 'Junior counsel', options: { 150: '£150: Attorney General’s London A Panel rate', 175: '£175: lowest published minimum, Crown Office Chambers', 350: '£350: highest published minimum, Crown Office Chambers' }, own: 'Your own rate' },
    disciplines: {
      label: 'Technical experts: one expert for each discipline ticked',
      names: { fire: 'Fire engineering', arch: 'Architecture', me: 'Building services (mechanical and electrical)' },
      rateLabel: '{name} expert, rate in pounds an hour',
      some: '{n} {experts} at an average of {rate} an hour. Each expert’s time is set in the team table.',
      words: ['expert', 'experts'],
      none: 'No discipline is ticked, so technical experts are left out of the estimate.',
    },
  },
  team: {
    legend: 'The team and their time',
    note: 'Discussing and finding are minutes for each person each time an item is discussed. Reading is minutes for each person for each item over the whole matter. Bundling is hours for each person for each bundle. Untick anyone who is not involved.',
    columns: ['Person', 'Rate, £ an hour', 'Discussing, minutes each time', 'Finding earlier replies, minutes each time', 'Reading, minutes an item', 'Bundling, hours a bundle'],
    groups: { counsel: 'Counsel', solicitors: 'Solicitors', experts: 'Experts', client: 'Client team' },
    names: { kc: 'King’s Counsel', jun: 'Junior counsel', ptr: 'Partner', sa: 'Senior associate', asc: 'Associate', para: 'Paralegal', tex: 'Technical experts', qex: 'Quantum expert', dex: 'Delay expert', cm: 'Commercial manager', pm: 'Project manager', dir: 'Director' },
    fields: { rate: 'rate in pounds an hour', min: 'discussing, minutes each time', smin: 'finding earlier replies, minutes each time', read: 'reading, minutes an item', bund: 'bundling, hours a bundle' },
    texRate: 'Technical experts, average rate',
    noDiscipline: 'No discipline ticked',
    each: 'each technical expert',
  },
  meetings: {
    legend: 'Meetings',
    note: 'Conferences with counsel and experts’ meetings are kept by default. Mark a kind of meeting as replaceable only if part of it is the sharing of information that a written thread could do instead.',
    names: { conf: 'Conferences with counsel', exp: 'Experts’ and technical meetings', prog: 'Progress calls' },
    number: 'Number',
    length: 'Hours each',
    replaceable: 'A written thread could replace part of these',
    who: 'Who attends: {name}',
  },
  reductions: {
    legend: 'What a shared record might change',
    note: 'The share of each activity’s time that a shared, searchable record of the discussion might free, in a low, central and high case. The figure that might be freed uses the central case.',
    meeting: { label: 'Meeting reduction, central case', options: { 0: 'None (recommended)', 14: '14%: reported by the company (Shopify, 2023)', 18.9: '18.9%: commissioned by the vendor (Forrester for Microsoft, 2019)' }, own: 'Your own figure' },
    value: { label: 'Value placed on the time freed', options: { 1: 'All of it, at the rates shown', 0.8: '80%, as in a study commissioned by Thomson Reuters (Forrester, 2024)', 0.25: '25%, as in a study commissioned by Microsoft (Forrester, 2019)' } },
    noneReplaceable: ' (none replaceable)',
  },
  results: {
    title: 'Estimate',
    label: 'Professional time on the evidence, one matter',
    labelMany: 'Professional time on the evidence, across {n} matters',
    sub: '{hours} hours, about {days} working days',
    subEach: '; {cost} a matter',
    homeFigure: 'Discussing the evidence comes to {cost}: the figure modelled in the [collaboration section of our home page](/#collaboration).',
    discussion: 'Of which discussing the evidence: {cost}.',
    freedSub: '{hours} hours, {share} of the cost above. Low case {lo}; high case {hi}.',
    partValue: 'Counting {share} of the time freed as value, as a study commissioned by a vendor does. The full value of that time is {full}.',
    firm: {
      title: 'How firm is this figure?',
      byReduction: 'Time that might be freed in the central case, by the basis of its reduction',
      byRate: 'Cost of the time, by the basis of its rate',
      line: '{pub} of the central figure rests on published research. The minutes, hours and meeting patterns are estimates in every case: VeriCase’s in the starting points, or yours. The checks below test them.',
      lineNone: 'The minutes, hours and meeting patterns are estimates in every case: VeriCase’s in the starting points, or yours.',
    },
    checks: {
      title: 'Do the time estimates hold up?',
      intro: 'Each check takes the busiest person on the team and compares their time on one activity with a published study, averaged over the length of the matter.',
      titles: { search: 'Finding earlier replies', email: 'Discussing the evidence', meet: 'Meetings', total: 'All evidence work', bund: 'Bundling', adj: 'Length of an adjudication' },
      units: { search: 'finding earlier replies', email: 'discussing the evidence', meet: 'in meetings', total: 'on evidence work' },
      line: 'Busiest: {person}, {hours} hours a week {unit} over {weeks}.',
      bund: '{hours} hours of team time for each bundle.',
      adj: 'Your matter runs for {weeks}, about {days} days.',
      status: { ok: 'Below the benchmark', fits: 'Within a working week', warn: 'Above the benchmark', cap: 'More than a working week', ctx: 'For context' },
      bench: {
        search: '599 construction leaders reported spending 5.5 hours a week, 13.4% of their working time, looking for project data and information of all kinds (PlanGrid with FMI, 2018).',
        email: 'Knowledge workers spend about 28% of the working week, 13 hours of a week of 46.5 hours, reading and answering email of all kinds (McKinsey Global Institute, 2012).',
        meet: '632 employees reported an average of 18 hours a week in meetings of all kinds (Rogelberg with Otter.ai, 2022; self-reported, and published by the vendor).',
        total: 'A full working week of five days of 7.5 hours, the basis of the timesheet.',
        bund: 'The High Court held it plainly unreasonable to spend 55, 82 or 85 hours assembling the six bundles for each of three hearings, and allowed 50 hours of work on the documents for each of two hearings (*Hon Shu Pang v Justin Zinda* [2024] EWHC 176 (KB), paragraphs 17 and 21; the costs of a litigant in person).',
        adj: '48% of respondents said that adjudications in the past year were typically completed within 29 to 42 days of the referral notice (King’s College London with the Adjudication Society, *Construction Adjudication in the United Kingdom*, November 2024). Your length may include work before the referral.',
      },
    },
    activity: { title: 'Where the time goes', columns: ['Activity', 'Hours', 'Cost', 'Central', 'Might be freed'] },
    people: { title: 'Who spends it', columns: ['Person', 'Rate', 'Hours', 'A week', 'Cost', 'Might be freed'], note: 'A week is each person’s hours on one matter, averaged over its length.' },
    scenarios: {
      title: 'Low, central and high',
      intro: 'The value that might be freed in each case, by activity. The spread shows where the uncertainty lies.',
      columns: ['Activity', 'Low', 'Central', 'High'],
      hours: 'Hours freed',
      share: 'Share of cost',
    },
  },
  method: {
    title: 'How the estimate is built',
    items: [
      'Discussing: items, times the number of times each is discussed, times each person’s minutes, divided by 60.',
      'Finding earlier replies: the same, using each person’s finding minutes.',
      'Reading: items, times each person’s reading minutes for each item, divided by 60.',
      'Bundling: bundles, times each person’s hours for each bundle.',
      'Meetings: the number, times the hours each, times the people attending.',
      'Each person’s hours are priced at their rate. Technical experts count once for each discipline ticked, each at their own rate.',
      'Time freed is each activity’s hours multiplied by its reduction. Meeting reductions apply only to the kinds of meeting marked replaceable.',
      'The value of the time freed is that time priced at the same rates, multiplied by the share of it you choose to count.',
      'The checks divide each person’s hours on one matter by its length in weeks. More than one matter multiplies one matter by the number of matters.',
    ],
  },
};

// The evidence cost calculator: built up from each person's hours on one matter.
export const EVIDENCE_COST = {
  path: '/evidence-cost',
  h1: 'What does the evidence cost your team?',
  intro: [
    'Set the hours your counsel, solicitors, experts and project team spend on the evidence in a construction dispute: discussing it, finding earlier replies, reading it, meeting about it and bundling it. The calculator prices that time and shows how much of it a shared, searchable record of the evidence and its discussion might free.',
    'Every rate and reduction is labelled with its basis, so you can see which parts of the result rest on published research and which are assumptions you can change. Nothing you enter leaves your browser.',
  ],
  other: 'Prefer to build the cost up from each item of evidence? Use the [discussion cost calculator](/discussion-cost).',
  matter: {
    legend: 'Your matter',
    note: 'Start from the closest kind of matter, then adjust anything. A starting point sets the team, their hours and the meetings; it leaves your rates and reductions as they are.',
    startLegend: 'Kind of matter',
    starts: { adj: 'Adjudication', large: 'Large adjudication', serial: 'Serial adjudications', tcc: 'Court claim' },
    status: {
      adj: 'Adjudication: junior counsel, a partner and an associate, quantum and delay experts, your commercial manager and a paralegal, at 40% of the large adjudication’s hours. All are VeriCase estimates.',
      large: 'Large adjudication: a team of fourteen, with VeriCase’s estimates of their hours and meetings. Change any figure to match your matter.',
      serial: 'Serial adjudications: three large adjudications on one project. No credit is taken for reusing discussion between them.',
      tcc: 'Court claim in the Technology and Construction Court: the large adjudication’s team at three times the hours, with a progress call every fortnight over two years. All are VeriCase estimates.',
    },
    edited: '{start}, edited. Choose it again to reload its team, hours and meetings.',
    matters: { label: 'Number of matters', hint: 'Multiplies one matter. Use 3 or 4 for serial adjudications on one project. No credit is taken for reusing discussion between matters.' },
    searchShare: {
      label: 'Finding earlier replies',
      output: '{n}% of email time',
      hint: 'The time spent finding the earlier reply, drawing or attachment before answering. The nearest benchmark is 5.5 hours a week spent looking for project data (PlanGrid with FMI, 2018).',
    },
    rateBasis: { label: 'Solicitors’ and paralegals’ rates', options: { l1: 'Guideline rates 2026, London 1', l2: 'Guideline rates 2026, London 2', l3: 'Guideline rates 2026, London 3', n1: 'Guideline rates 2026, National 1', n2: 'Guideline rates 2026, National 2', own: 'Enter your own rates' } },
    dayLen: { label: 'Hours in a working day' },
    rateHint: 'Guideline rates are the HMCTS solicitors’ guideline hourly rates in effect from 01 January 2026, which the courts use as a starting point for the summary assessment of costs. Rates charged in practice may be higher: choose your own rates to enter them in the team table.',
    recap: {
      label: 'Value only part of the time freed',
      field: 'Share of the time freed that is valued, per cent',
      hint: 'Hours freed are not always hours billed less. Studies commissioned by software vendors count only part of the time saved as value: Forrester counted 25% in a 2019 study for Microsoft and 80% in a 2024 study for Thomson Reuters. Tick to value only the share you choose; the hours freed are unaffected.',
    },
  },
  team: {
    legend: 'Your team',
    note: 'Tick who is on the matter and set their hours on one matter. Finding earlier replies is worked out from the time on email; meetings are set separately below.',
    columns: ['Person and rate basis', 'Rate, £ an hour', 'Discussing by email, hours', 'Reading and review, hours', 'Bundling, hours'],
    groups: { counsel: 'Counsel', solicitors: 'Solicitors', experts: 'Experts', client: 'Client team' },
    names: { kc: 'Leading counsel (King’s Counsel)', junior: 'Junior counsel', partner: 'Partner', sa: 'Senior associate', assoc: 'Associate', para: 'Paralegal', tech1: 'Technical expert 1', tech2: 'Technical expert 2', tech3: 'Technical expert 3', quantum: 'Quantum expert', delay: 'Delay expert', cm: 'Commercial manager', pm: 'Project manager', dir: 'Director' },
    fields: { rate: 'rate in pounds an hour', email: 'discussing by email, hours', read: 'reading and review, hours', bund: 'bundling, hours' },
    foot: 'Team on the matter',
    people: ['person', 'people'],
  },
  meetings: {
    legend: 'Meetings',
    note: 'Set each kind of meeting and who attends. By default every meeting stays as it is: no independent study measures how much meeting time a written record of the discussion replaces. Choose a reduction only where a written thread could do the meeting’s work.',
    names: { conf: 'Conferences with counsel', expert: 'Experts’ and technical meetings', progress: 'Progress calls' },
    hints: {
      conf: 'Usually kept: advice and strategy need the meeting. The TCC Guide asks parties to consider in every case whether attendance by their most senior advocates is reasonably required at a case management conference (paragraph 5.8.1); the same discipline applies here.',
      expert: 'Experts’ discussions still need a meeting. The exchanges about documents around them are the part a shared thread might take over.',
      progress: 'Updates on progress are the meetings most readily shortened, or replaced by a written thread.',
    },
    number: 'Meetings',
    length: 'Hours each',
    reduction: 'Reduction with a shared record',
    locked: 'Counted only when the central case includes assumptions: untick “Central case: published research only” under Reductions to choose one.',
    options: { 0: 'None (the default)', 14: '14%: reported by the company (Shopify, 2023)', 18.9: '18.9%: commissioned by the vendor (Forrester for Microsoft, 2019)', 25: '25%: your own estimate', 50: '50%: your own estimate', 100: '100%: replaced entirely by written threads' },
    summary: '{n} {attendees}, {hours} person-hours, {cost} on one matter.',
    attendees: ['attendee', 'attendees'],
    who: 'Who attends: {name}',
  },
  reductions: {
    legend: 'Reductions',
    note: 'The share of each activity’s time that a shared record might free, in per cent. The central case gives the figure that might be freed; the low and high cases set the range in the results. A central figure you change is marked as yours.',
    perMeeting: 'Set for each meeting above',
    restore: 'Restore the evidence-based defaults',
  },
  results: {
    title: 'Estimate',
    label: 'Professional time on the evidence, one matter',
    labelMany: 'Professional time on the evidence, across {n} matters',
    sub: '{hours} hours, about {days} working days of {day} hours.',
    freedSub: '{hours} hours, about {days} working days ({share} of the cost above).',
    allPublished: 'All of it rests on published research.',
    somePublished: '{pub} of it rests on published research alone.',
    nonePublished: 'None of it rests on published research.',
    setReduction: 'Set a reduction to see the time that might be freed.',
    partValue: 'Counting {share} of the time freed as value. The hours freed are unaffected.',
    tickSomeone: 'Tick at least one person on the team and give them some hours.',
    activity: { title: 'Where the time comes from', intro: 'Value that might be freed, by activity.' },
    grade: { title: 'What the result rests on', intro: 'Value that might be freed, by the evidence behind each reduction used.', label: 'Published research' },
    byActivity: { title: 'By activity', columns: ['Activity', 'Hours', 'Cost', 'Reduction', 'Hours freed', 'Value freed'] },
    byPerson: { title: 'By person', columns: ['Person', 'Rate', 'Hours', 'Hours freed', 'Value freed'] },
    range: {
      title: 'Range',
      columns: ['Case', 'One matter', 'Across {n} matters'],
      rows: { lo: 'Low', c: 'Your settings', hi: 'High' },
      note: 'The low case uses the bottom of each range, with no reduction in meetings, reading or bundling unless you set one. The high case uses the top of each range, and the higher of your setting and the high figure for every meeting.',
    },
  },
  method: {
    title: 'How the figures work',
    items: [
      'The cost of the time is hours multiplied by each person’s rate. Finding earlier replies is a share of each person’s time on email. Meeting time is the number of meetings, multiplied by their length and by each attendee on the team.',
      'Time freed is each activity’s hours multiplied by its reduction. Its value is that time multiplied by the rate, scaled by the share you choose to value if you tick that option.',
      'More than one matter multiplies one matter by the number of matters. No credit is taken for reusing discussion across matters.',
      'The default team, hours and meeting pattern describe a large construction adjudication and are VeriCase estimates.',
      'Leading counsel’s £600 an hour is an assumption: published judgments record counsel’s brief fees rather than hourly rates. Junior counsel’s £150 is the Attorney General’s London A Panel rate, a discounted public-sector rate; rates charged to private clients are typically higher, so enter your own if you know them.',
      'In statutory adjudication each party usually bears its own costs, so the cost of this time is not usually recoverable from the other party. The result is an estimate of time and its cost, not a measured saving.',
    ],
  },
};

// Sources shared by both pages (verified for publication; see the capability register, E15).
export const CALCULATOR_SOURCES = {
  title: 'Notes and sources',
  items: [
    'Discussing and finding earlier replies: McKinsey Global Institute, *The social economy: Unlocking value and productivity through social technologies*, July 2012 (Exhibit 20), estimated that social technologies could free 25% to 30% of the time that interaction workers (high-skill knowledge workers) spend reading and answering email, and 30% to 35% of the time they spend searching for and gathering information. The central case uses the lower figures; the low cases (15% and 20%) are VeriCase discounts. These are modelled estimates for knowledge workers generally, drawn from data of 2009, not measured results in construction or law, and they predate VeriCase.',
    'Meetings: no independent study measures how much meeting time a shared record of the discussion removes, so the central case counts none. The optional figures are a 14% fall in the average time each person spent in meetings at Shopify in the first five months of 2023, compared with the same months of 2022, which followed a policy of cancelling recurring meetings rather than a software tool (its chief financial officer, interviewed in *Fortune*, 14 July 2023); and an 18.9% average fall in the number of meetings in a study commissioned by Microsoft (Forrester Consulting, *The Total Economic Impact of Microsoft Teams*, April 2019).',
    'Reading and bundling: VeriCase assumptions (5% and 10% in the central case when assumptions are included); no study measures them. For context, the review of documents typically accounted for about 73% of the cost of producing electronic disclosure in 57 productions studied by the RAND Institute for Civil Justice (*Where the Money Goes*, 2012); and in *White Winston Select Asset Funds LLC v Mahon* [2019] EWHC 1381 (Ch), some 200 to 250 of the more than 8,000 pages in the chronological files were referred to at trial (paragraph 43).',
    'Value placed on time freed: studies of workplace software commonly count only part of the time saved as value. Forrester’s study of Thomson Reuters legal research tools for an in-house legal department (November 2024) counted 80%; its study of Microsoft Teams (April 2019) counted 25%. Both were commissioned by the vendor.',
    'Solicitors’ rates: HMCTS solicitors’ guideline hourly rates in effect from 01 January 2026, by band and grade (A partner, B senior associate, C associate, D trainee or paralegal). The courts use guideline rates as a starting point for the summary assessment of costs; actual charges may be higher. The option of rates claimed in a Technology and Construction Court case uses the hourly rates claimed by the claimant’s solicitors in *Lime Technology Ltd v Liverpool City Council* [2025] EWHC 2037 (TCC), a procurement claim (partner £1,345.50, senior associate £895.50, associate £463.50), which the judge described as “at the upper range of any possible range” (paragraph 14); no paralegal rate was recorded, so the London 1 Grade D rate is used.',
    'Counsel: there is no official guideline hourly rate for barristers. Junior counsel’s £150 is the Attorney General’s London A Panel rate for government civil work from 01 April 2025, a discounted public-sector rate. £175 and £350 are the lowest and highest of the minimum hourly rates, before value added tax, that Crown Office Chambers publishes for public access work in cases valued under £100,000, depending on the barrister’s seniority (checked 06 October 2026). King’s Counsel at £600 is a VeriCase assumption, with £1,000 as an upper sensitivity; £270 is the Attorney General’s rate from 01 April 2025 for a King’s Counsel of ten years or more whose current rate is £200 to £269, a public-sector floor. Published judgments generally record counsel’s brief fees rather than hourly rates.',
    'Experts: £253.73 is the average hourly rate for report writing reported by expert witnesses working in the civil courts, across all disciplines, in the Bond Solon Expert Witness Survey 2025 (published 07 November 2025; 525 respondents). No current survey reports rates by discipline; replace it with the rates your experts quote.',
    'Client team: the commercial manager’s £47.50 is an estimate of the internal cost to the contractor, derived from a gross salary of £57,000 with employer National Insurance, the statutory minimum employer pension contribution and a 25% overhead, over 1,740 working hours a year. The project manager’s £45 and the director’s £85 are VeriCase assumptions.',
    'Benchmarks for the checks: PlanGrid with FMI, *Construction Disconnected*, 2018 (599 construction industry leaders; 5.5 hours a week looking for project data and information); McKinsey Global Institute, July 2012 (28% of the working week on email); Rogelberg with Otter.ai, *The Cost of Unnecessary Meeting Attendance*, 2022 (632 employees; 18 hours a week in meetings); *Hon Shu Pang v Justin Zinda* [2024] EWHC 176 (KB), paragraphs 17 and 21; Nazzini and Godhe, King’s College London with the Adjudication Society, *Construction Adjudication in the United Kingdom*, November 2024. Each benchmark covers more than work on the evidence, so the estimates should sit below it.',
    'Starting points: team sizes, minutes, hours and meeting patterns are VeriCase estimates based on practitioner experience, chosen as lower bounds. The same times for each person are used in every starting point of a calculator, so a larger matter costs more only because it has more items, discussions, bundles, meetings or people.',
    'Recovery of costs: in statutory adjudication each party usually bears its own legal and expert costs. In litigation and arbitration some costs may be recoverable from, or payable to, the other party.',
    'The figures show professional time and its cost at the rates shown, and the time that might be freed in each case. They are illustrations: VeriCase has not measured the time it saves, and whether time freed becomes a saving depends on how the time is billed and used.',
  ],
};
