// The Chronology Lens workbench and File Manager (Chapter II, Fig. 3).
// Nothing here is real: see note A.
import { APP_WINDOW } from '@/content/records';

export const WORKBENCH = {
  window: APP_WINDOW,
  tabs: ['Chronology Lens™', 'File Manager'],
  archive: 'Archive_Contractor.pst (sample)',
  ledger: [
    ['Messages parsed', 312],
    ['Attachments extracted', 146],
    ['Threads rebuilt', 41],
    ['Quoted passages folded', 187],
    ['Near-duplicates removed from review', 58],
    ['Other projects excluded', 23],
    ['Pages read by OCR', 36],
  ],
  view: ['Cards', 'Table'],
  dateWindow: { label: 'Date window', from: '2025-02-01', to: '2025-06-30' },
  smartFilter: 'Smart Filter',
  excludeLabel: 'Exclude keywords',
  exclude: ['newsletter', 'canteen', 'parking'],
  excludedByKeyword: 14,
  // How the 14 split by keyword, so that removing a keyword chip can be counted (illustrative).
  excludedByEachKeyword: { newsletter: 9, canteen: 1, parking: 4 },
  keywordMarker: '{n} items excluded by keyword',
  keywordMarkerOne: '1 item excluded by keyword',
  parties: ['Employer’s Agent', 'Contractor', 'Façade Sub-Contractor', 'Supplier'],
  createBundle: 'Create bundle',
  createBundleNote: 'Create bundle works as shown in Chapter III.',
  hiddenMarker: '{n} entries hidden by filter',
  hiddenMarkerOne: '1 entry hidden by filter',
  // Below 768 px the list opens on its first entries, with a button for the rest. From 768 px it
  // scrolls inside the frame, and a count under the fade says how many entries lie below.
  showAll: 'Show all {n} entries',
  showFewer: 'Show fewer entries',
  moreEntries: '{n} more entries',
  moreEntriesOne: '1 more entry',
  entries: ['EV-0131', 'EV-0133', 'EV-0138', 'EV-0139', 'EV-0144', 'EV-0147', 'EV-0151', 'EV-0153'],
  // Parties that each entry involves, for the party chips.
  entryParties: {
    'EV-0131': ['Employer’s Agent', 'Contractor'],
    'EV-0133': ['Contractor', 'Façade Sub-Contractor'],
    'EV-0138': ['Façade Sub-Contractor', 'Contractor'],
    'EV-0139': ['Contractor'],
    'EV-0144': ['Contractor'],
    'EV-0147': ['Supplier', 'Façade Sub-Contractor', 'Contractor'],
    'EV-0151': ['Contractor', 'Employer’s Agent'],
    'EV-0153': ['Employer’s Agent', 'Contractor'],
  },
  asReceived: 'As received',
  asAuthored: 'As authored',
  quotedChip: 'Quoted history folded ({n})',
  // The live evidence drawer (as seen in the app on 25 September 2026).
  drawer: {
    content: 'Content',
    contentModes: ['Text', 'HTML'],
    properties: 'Properties',
    tags: 'Tags',
    tagPlaceholder: 'Add a tag and press Enter',
    noTags: 'No tags yet',
    mentions: 'Mentions',
    mentionPlaceholder: 'Search users to mention',
    discussionCreated: 'A discussion with the mentioned users about this evidence has been created.',
    goToDiscussion: 'Go to Discussion',
    relevance: 'Relevance',
    relevanceHelp: 'Mark this evidence as not relevant to exclude it and its attachments from search results.',
    markNotRelevant: 'Mark as Not Relevant',
    undo: 'Undo',
    sampleTags: { 'EV-0139': ['Notice'], 'EV-0138': ['Lead time'], 'EV-0151': ['Notice'] },
  },
  notRelevant: {
    id: 'N-4',
    title: 'Weekly canteen menu',
    date: '2025-03-17',
    attachment: 'menu.pdf',
    result: 'Not relevant: excluded from search with its attachment (menu.pdf)',
  },
  fileManager: {
    heading: 'Attachments by type',
    counts: [
      ['PDF', 64],
      ['Images', 52],
      ['DOC and DOCX', 19],
      ['Spreadsheets', 11],
    ],
    showNoise: 'Show Noise',
    files: [
      { name: 'Delivery_schedule.pdf', type: 'PDF', from: 'EV-0147', size: '212 KB' },
      { name: 'Site_Diary_March_2025.pdf', type: 'PDF', from: 'EV-0144', size: '3.4 MB' },
      { name: 'Bracket_type_B_datasheet.pdf', type: 'PDF', from: 'EV-0133', size: '486 KB' },
      { name: 'Facade_sample_board_photo.jpg', type: 'Images', from: 'EV-0131', size: '1.2 MB' },
      { name: 'Bracket_quantities_L3-L6.xlsx', type: 'Spreadsheets', from: 'EV-0139', size: '38 KB' },
    ],
    noise: [
      { name: 'image001.png', note: 'signature image' },
      { name: 'logo.gif', note: 'signature image' },
    ],
    noiseLabel: 'Noise',
  },
  status: {
    hidden: '{n} entries hidden by filter',
    allShown: 'All {n} entries shown',
    firstShown: 'First {m} of {n} entries shown',
    noiseShown: 'Noise shown: 2 attachments',
    notRelevant: 'Item marked Not Relevant; 1 attachment excluded from search',
  },
};
